'use client';

import { motion, useReducedMotion } from 'framer-motion';

/**
 * HiveAnimation
 * =============
 * A honeycomb lattice with a glowing tangerine signal that draws itself along the
 * grid edges, branches, closes the occasional cell, fades, and loops.
 *
 * How the grid stays seamless
 * ---------------------------
 * The <pattern> tile below draws only the LEFT HALF of each hexagon (three edges).
 * Neighbouring tiles supply the other half, so every edge is drawn exactly once.
 * Drawing whole hexagons would double every shared edge and, at 5% opacity, the
 * doubled lines would render at roughly 10% and the grid would look striped.
 *
 * How the signal follows the grid
 * -------------------------------
 * The path coordinates are not hand-drawn. They were generated by walking the real
 * lattice graph, so every segment lies exactly on a hexagon edge. That is why the
 * glow reads as a signal travelling through the structure rather than a squiggle
 * laid on top of it.
 *
 * The walk is confined to x > 700 in the 1440-wide viewBox, so it occupies the photo
 * half of the hero and leaves the headline column alone. Rotating the whole SVG would
 * have moved it too, but it would also tilt the base grid off-horizontal, which reads
 * as a rendering fault rather than a decision.
 *
 * Framer Motion animates `pathLength`, which under the hood drives strokeDasharray
 * and strokeDashoffset. Opacity is keyframed separately so each path draws in,
 * holds, then dissolves before the loop restarts.
 *
 * Cost and restraint
 * ------------------
 * - `hidden lg:block`: never rendered on phones, where it would cost battery for
 *   decoration nobody asked for.
 * - `useReducedMotion`: visitors who ask for less motion get the static grid only.
 * - `pointer-events-none` and `aria-hidden`: invisible to clicks and screen readers.
 */

const TILE_W = 72.00;
const TILE_H = 41.57;
const GRID_D = 'M-24.0 0.0 L-48.0 0.0 L-60.0 -20.8 L-48.0 -41.6 M-24.0 41.6 L-48.0 41.6 L-60.0 20.8 L-48.0 0.0 M-24.0 83.1 L-48.0 83.1 L-60.0 62.4 L-48.0 41.6 M-24.0 124.7 L-48.0 124.7 L-60.0 103.9 L-48.0 83.1 M12.0 -20.8 L-12.0 -20.8 L-24.0 -41.6 L-12.0 -62.4 M12.0 20.8 L-12.0 20.8 L-24.0 0.0 L-12.0 -20.8 M12.0 62.4 L-12.0 62.4 L-24.0 41.6 L-12.0 20.8 M12.0 103.9 L-12.0 103.9 L-24.0 83.1 L-12.0 62.4 M48.0 0.0 L24.0 0.0 L12.0 -20.8 L24.0 -41.6 M48.0 41.6 L24.0 41.6 L12.0 20.8 L24.0 0.0 M48.0 83.1 L24.0 83.1 L12.0 62.4 L24.0 41.6 M48.0 124.7 L24.0 124.7 L12.0 103.9 L24.0 83.1 M84.0 -20.8 L60.0 -20.8 L48.0 -41.6 L60.0 -62.4 M84.0 20.8 L60.0 20.8 L48.0 0.0 L60.0 -20.8 M84.0 62.4 L60.0 62.4 L48.0 41.6 L60.0 20.8 M84.0 103.9 L60.0 103.9 L48.0 83.1 L60.0 62.4 M120.0 0.0 L96.0 0.0 L84.0 -20.8 L96.0 -41.6 M120.0 41.6 L96.0 41.6 L84.0 20.8 L96.0 0.0 M120.0 83.1 L96.0 83.1 L84.0 62.4 L96.0 41.6 M120.0 124.7 L96.0 124.7 L84.0 103.9 L96.0 83.1';

const PATHS = [
  { id: 'trunk', width: 2.2, delay: 0, duration: 7.0, d: 'M732.0 103.9 L744.0 124.7 L732.0 145.5 L744.0 166.3 L732.0 187.1 L744.0 207.8 L732.0 228.6 L744.0 249.4 L732.0 270.2 L744.0 291.0 L732.0 311.8 L744.0 332.6 L732.0 353.3 L744.0 374.1 L732.0 394.9 L744.0 415.7 L732.0 436.5 L744.0 457.3 L732.0 478.0 L744.0 498.8 L768.0 498.8 L780.0 519.6 L804.0 519.6 L816.0 540.4 L840.0 540.4 L852.0 561.2 L840.0 582.0 L852.0 602.8 L840.0 623.5 L852.0 644.3 L840.0 665.1 L852.0 685.9 L876.0 685.9 L888.0 706.7 L876.0 727.5 L888.0 748.2 L876.0 769.0 L888.0 789.8 L912.0 789.8 L924.0 810.6 L948.0 810.6 L960.0 831.4 L984.0 831.4 L996.0 852.2 L1020.0 852.2 L1032.0 831.4 L1056.0 831.4 L1068.0 852.2 L1092.0 852.2 L1104.0 831.4 L1128.0 831.4 L1140.0 852.2 L1164.0 852.2 L1176.0 831.4 L1200.0 831.4 L1212.0 852.2 L1236.0 852.2' },
  { id: 'branchA', width: 1.6, delay: 1.5, duration: 5.0, d: 'M732.0 311.8 L744.0 291.0 L768.0 291.0 L780.0 270.2 L804.0 270.2 L816.0 249.4 L804.0 228.6 L816.0 207.8 L804.0 187.1 L816.0 166.3 L804.0 145.5 L780.0 145.5 L768.0 166.3 L780.0 187.1 L768.0 207.8 L780.0 228.6 L804.0 228.6 L816.0 207.8 L840.0 207.8' },
  { id: 'branchB', width: 1.6, delay: 2.6, duration: 4.6, d: 'M840.0 582.0 L852.0 602.8 L876.0 602.8 L888.0 623.5 L912.0 623.5 L924.0 602.8 L948.0 602.8 L960.0 623.5 L984.0 623.5 L996.0 602.8 L1020.0 602.8 L1032.0 623.5 L1056.0 623.5 L1068.0 602.8 L1092.0 602.8 L1104.0 623.5 L1128.0 623.5' },
  { id: 'branchC', width: 1.4, delay: 3.6, duration: 4.0, d: 'M948.0 810.6 L960.0 789.8 L984.0 789.8 L996.0 810.6 L984.0 831.4 L996.0 852.2 L1020.0 852.2 L1032.0 831.4 L1056.0 831.4 L1068.0 810.6 L1092.0 810.6 L1104.0 831.4 L1092.0 852.2 L1068.0 852.2 L1056.0 831.4' },
  { id: 'ringA', width: 2.0, delay: 2.2, duration: 2.6, d: 'M744.0 457.3 L732.0 478.0 L708.0 478.0 L696.0 457.3 L708.0 436.5 L732.0 436.5 Z' },
  { id: 'ringB', width: 2.0, delay: 4.4, duration: 2.6, d: 'M888.0 748.2 L876.0 769.0 L852.0 769.0 L840.0 748.2 L852.0 727.5 L876.0 727.5 Z' },
];

type Props = {
  /** Extra classes for the wrapper, e.g. an opacity override per section. */
  className?: string;
};

export default function HiveAnimation({ className = '' }: Props) {
  const reduceMotion = useReducedMotion();

  return (
    <div
      aria-hidden
      className={`pointer-events-none absolute inset-0 z-0 hidden overflow-hidden lg:block ${className}`}
    >
      <svg
        viewBox="0 0 1440 900"
        preserveAspectRatio="xMidYMid slice"
        className="h-full w-full"
      >
        <defs>
          <pattern
            id="hive-grid"
            width={TILE_W}
            height={TILE_H}
            patternUnits="userSpaceOnUse"
          >
            <path
              d={GRID_D}
              fill="none"
              stroke="#2B3C5A"
              strokeOpacity={0.05}
              strokeWidth={1}
            />
          </pattern>

          {/* Neon bloom: blur the stroke, stack it twice for intensity, then lay
              the crisp stroke back on top so the line core stays sharp. */}
          <filter id="hive-glow" x="-25%" y="-25%" width="150%" height="150%">
            <feGaussianBlur stdDeviation="5" result="blur" />
            <feMerge>
              <feMergeNode in="blur" />
              <feMergeNode in="blur" />
              <feMergeNode in="SourceGraphic" />
            </feMerge>
          </filter>

          {/* Horizontal fade, not radial. The signal is fully masked out across the
              headline column, ramps in over the gutter, and eases off again at the
              far edge so it never terminates in a hard vertical line. Move the 42%
              and 60% stops together to widen or narrow the clear zone. */}
          <linearGradient id="hive-fade" x1="0" y1="0" x2="1" y2="0">
            <stop offset="0%" stopColor="#fff" stopOpacity="0" />
            <stop offset="42%" stopColor="#fff" stopOpacity="0" />
            <stop offset="60%" stopColor="#fff" stopOpacity="0.85" />
            <stop offset="88%" stopColor="#fff" stopOpacity="1" />
            <stop offset="100%" stopColor="#fff" stopOpacity="0.15" />
          </linearGradient>
          <mask id="hive-mask">
            <rect width="1440" height="900" fill="url(#hive-fade)" />
          </mask>
        </defs>

        <rect width="1440" height="900" fill="url(#hive-grid)" />

        {!reduceMotion && (
          <g mask="url(#hive-mask)" filter="url(#hive-glow)">
            {PATHS.map((p) => (
              <motion.path
                key={p.id}
                d={p.d}
                fill="none"
                stroke="#FF8F00"
                strokeWidth={p.width}
                strokeLinecap="round"
                strokeLinejoin="round"
                initial={{ pathLength: 0, opacity: 0 }}
                animate={{ pathLength: [0, 1, 1], opacity: [0, 1, 0] }}
                transition={{
                  // 0 -> 0.62 draws, 0.62 -> 0.82 holds, then it fades out
                  times: [0, 0.62, 1],
                  duration: p.duration,
                  delay: p.delay,
                  ease: 'easeInOut',
                  repeat: Infinity,
                  repeatDelay: 1.4,
                }}
              />
            ))}
          </g>
        )}
      </svg>
    </div>
  );
}
